name: Node.js CI

on:
  push:
    branches:
      - main      # Trigger on pushes to main branch
  pull_request:
    branches:
      - main      #targeting main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'   

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test
   
